// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMaBt8SHWzdKP9OHkWizXBK2TrjL3dixY',
    appId: '1:741972565994:web:2b1d342fb53d24971a9c93',
    messagingSenderId: '741972565994',
    projectId: 'caloriepay',
    authDomain: 'caloriepay.firebaseapp.com',
    storageBucket: 'caloriepay.appspot.com',
    measurementId: 'G-VRX07SXZEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFyvt3qyPGADsqsIXWuFWjNBiUdAoS79c',
    appId: '1:741972565994:android:0389ab93f4856c091a9c93',
    messagingSenderId: '741972565994',
    projectId: 'caloriepay',
    storageBucket: 'caloriepay.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKWYLlXfQcoF2GVlXRpaOxB67wuMTSlAo',
    appId: '1:741972565994:ios:aeacb9b3ede4551c1a9c93',
    messagingSenderId: '741972565994',
    projectId: 'caloriepay',
    storageBucket: 'caloriepay.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKWYLlXfQcoF2GVlXRpaOxB67wuMTSlAo',
    appId: '1:741972565994:ios:aeacb9b3ede4551c1a9c93',
    messagingSenderId: '741972565994',
    projectId: 'caloriepay',
    storageBucket: 'caloriepay.appspot.com',
    iosBundleId: 'com.example.test',
  );
}
